### ISSUE TITLE
build.sh files are incomplete

### ISSUE THREAD

**Issue by tveijola** [mbuet2ner/JEasyCrypto#18]
The build.sh files:
    /JEasyCryptoClient/build.sh,
    /JEasyCryptoConsole/build.sh and
    /JEasyCryptoServer/build.sh
refrence the "bin" folder, which does not exist in the above folders if not manually created.

Proposed fix:
    add "mkdir bin" as the first line of each .sh file mentioned above.

**Comment by mbuet2ner** [comment]
Thanks for the input @tveijola .
We are happy to review a pull request that fixes the issue :+1:

**Comment by mbuet2ner** [comment]
Fixed with #19
