### ISSUE TITLE
Wrong text in decrypting console application

### ISSUE THREAD

**Issue by tvuolio** [mbuet2ner/JEasyCrypto#23]
When the class EasyCryptoConsole requests to choose between encryption or decryption, it asks to provide **encryption** method, regardless of whether the user chooses "d" or "e". 

In line 25:
String e = console.readLine("Please enter text to be encrypted > ");
The above console output should depend on the input character given in the line 24: 
String d = console.readLine("Do you wish to encrypt or decrypt (e or d)? > ");

This issue needs to be fixed.

**Comment by mbuet2ner** [comment]
Yes, you are right. Either a modified `e` should be used (with reference to both, or none), or we shold add another variable for that.
Thank you!

**Comment by mbuet2ner** [comment]
Fixed with #27!
