### ISSUE TITLE
A wrong user input breaks the console app

### ISSUE THREAD

**Issue by tvuolio** [mbuet2ner/JEasyCrypto#28]
In the Console, the wrong user input is not handled and the execution breaks immediately. 
Example: 
Do you wish to encrypt or decrypt (e or d)? > k
>return 
>program breaks

This is related to the same lines as in the fix of issue #27

**Comment by Stupastian** [comment]
We agree with this issue. Program should give feedback to the user when input is not acceptable and maybe ask input again. We also propose additional choice that allows user to exit console application immediately.
We can implement a solution that asks input until one of the suitable choices is given.
Example:
What do wish to do? (e : encrypt, d : decrypt, q : quit) >

**Comment by mbuet2ner** [comment]
Closed with #32
