### ISSUE TITLE
Adapt windows build/ start scripts windows to new JSON library

### ISSUE THREAD

**Issue by mbuet2ner** [mbuet2ner/JEasyCrypto#37]
Build and start scripts are not adapted to our new JSON library unfortunately and therefore do not work correctly as of now.

Related to #34 #25

**Comment by kakezz** [comment]
Our group will take this issua

**Comment by tvuolio** [comment]
This is very urgent issue to be fixed, as the current version of the project does not allow the Windows users to participate.

**Comment by mbuet2ner** [comment]
Closed by #38 .
