### ISSUE TITLE
No build files for Windows

### ISSUE THREAD

**Issue by anttijuu** [mbuet2ner/JEasyCrypto#4]
The provided shell scripts can be used to build the encryption library jar file, server and the client. Also run the server and client. 

But these do not work in Windows, unless you are using a shell which supports bash. Git has a terminal window for Windows which supports bash, but the usual Windows Command prompt does not.

Anyone who could port the scripts to Windows? Or set up an alternative build system?

**Comment by tvuolio** [comment]
We can deliver the bat.files that can be used for building in Windows.

**Comment by tveijola** [comment]
This issue has been fixed by #25 and should be closed.

**Comment by mbuet2ner** [comment]
Thanks @tveijola . Fixed by #25 .
