### ISSUE TITLE
Why the client app user has to provide a local port number?

### ISSUE THREAD

**Issue by anttijuu** [mbuet2ner/JEasyCrypto#5]
When the client app starts, user enters the server address as well as the client port it uses to communicate with the server. 

Why user has to enter the port number? This is not good usability and it should be unnecessary. Just use any available port number the Socket API should be able to allocate.

**Comment by d2p** [comment]
That's easy, but as a first try... May I fix this one?

**Comment by mbuet2ner** [comment]
Fixed with #30 .
