### ISSUE TITLE
JSON parser is outdated

### ISSUE THREAD

**Issue by anttijuu** [mbuet2ner/JEasyCrypto#7]
The simple JSON parser used in the project is old and outdated. It should be replaced with something more modern and usable.

**Comment by HSadeghein** [comment]
We(Juho, Jussi, and Mohammad Hassan) will work on this

**Comment by jussityynela** [comment]
@mbuet2ner 
Hi, 
did you have any preference for the JSON parser library or should we just pick the JSON in Java 
that @anttijuu  suggested.

**Comment by mbuet2ner** [comment]
I think https://github.com/stleary/JSON-java looks fine. It is both under active development and widely used. Unless you have another suggestion, I would be fine with it.
Also the [license](https://github.com/stleary/JSON-java/blob/master/LICENSE) seems to be very permissive.

**Comment by jussityynela** [comment]
@mbuet2ner 
Thanks for the comment.
We do not have any other library to suggest. 
We will proceed by using the https://github.com/stleary/JSON-java and try get you a PR soon.

**Comment by mbuet2ner** [comment]
Fixed with #34 .
