### ISSUE TITLE
Logo/icon needed

### ISSUE THREAD

**Issue by mbuet2ner** [mbuet2ner/JEasyCrypto#8]
The current logo for the software is just very sloppy first try. Maybe there could be even a proper icon instead of a logo, so we can use it once #3 is being implemented?

A nice starting point for design may be [this](https://elementary.io/de/docs/human-interface-guidelines#iconography).

**Comment by smoberg** [comment]
Our group would like to make the logo.

**Comment by mbuet2ner** [comment]
Closed by #47 .
